spring:
  application:
    name: USER-INFORMATION-SERVICE
  data:
    rest:
      base-path: api

  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka